name: Update docs on new version (ipfs, ipfs-cluster, etc.)
on:
  workflow_dispatch:
  schedule:
    - cron: '30 5,17 * * *' # run every day at 5:30am and 5:30pm UTC
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ipfs-docs
        uses: actions/checkout@v2
      - name: Find latest go-ipfs tag
        id: latest_ipfs
        uses: ./.github/actions/latest-ipfs-tag
      - name: Update docs
        id: update
        uses: ./.github/actions/update-with-latest-versions
        with:
          latest_ipfs_tag: ${{ steps.latest_ipfs.outputs.latest_tag }}
      - name: pull-request
        uses: repo-sync/pull-request@65785d95a5a466e46a9d0708933a3bd51bbf9dde #v2.6.2
        if: ${{ steps.update.outputs.updated_branch }} # don't create a pr if there was no branch pushed
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ steps.update.outputs.updated_branch }}
          destination_branch: "main"
          pr_title: "Update documentation ${{ steps.latest_ipfs.outputs.latest_tag }}"
          pr_body: "Release Notes: https://github.com/ipfs/go-ipfs/releases/${{ steps.latest_ipfs.outputs.latest_tag }}"
          pr_label: "needs/triage,P0"

